### ISSUE TITLE
Error After Signing Apk

### ISSUE THREAD

**Issue by jaiswalakshansh** [51j0/Android-CertKiller#8]
I. Initiating APK extraction from device
   complete
------------------------------
I. Decompiling
   complete
------------------------------
I: Applying SSL bypass
   complete
------------------------------
I. Building New APK
   complete
------------------------------
I. Signing APK
   complete
------------------------------

Traceback (most recent call last):
  File "main.py", line 270, in <module>
    main(sys.argv[1:])
  File "main.py", line 257, in main
    runwizard()
  File "main.py", line 127, in runwizard
    signApplication("base/dist/base.apk",1)
  File "main.py", line 168, in signApplication
    command = 'mkdir '+myworkspace()+'/unpinnedapk/'+package[0]+millis+'/'
IndexError: list index out of range

**Comment by 51j0** [comment]
@jaiswalakshansh you can try the dev branch. I have revised the codebase. It should work now
